# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{plist}
  s.version = "3.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Nichols"]
  s.date = %q{2010-06-23}
  s.description = %q{Gem to generate plists}
  s.email = %q{josh@technicalpickles.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "docs/jamis-template.rb",
     "lib/plist.rb",
     "lib/plist/ascii.rb",
     "lib/plist/binary.rb",
     "lib/plist/generator.rb",
     "lib/plist/parser.rb",
     "test/assets/AlbumData.xml",
     "test/assets/Cookies.plist",
     "test/assets/commented.plist",
     "test/assets/example_data.bin",
     "test/assets/example_data.jpg",
     "test/assets/example_data.plist",
     "test/assets/example_data_ascii.plist",
     "test/assets/ruby.plist",
     "test/assets/test_data_elements.plist",
     "test/assets/test_empty_key.plist",
     "test/test_ascii.rb",
     "test/test_binary.rb",
     "test/test_data_elements.rb",
     "test/test_generator.rb",
     "test/test_generator_basic_types.rb",
     "test/test_generator_collections.rb",
     "test/test_parser.rb"
  ]
  s.homepage = %q{http://github.com/technicalpickles/the-perfect-gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{plist gem (binary)}
  s.test_files = [
    "test/test_ascii.rb",
     "test/test_binary.rb",
     "test/test_data_elements.rb",
     "test/test_generator.rb",
     "test/test_generator_basic_types.rb",
     "test/test_generator_collections.rb",
     "test/test_parser.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

